# Generated by Django 5.2.1 on 2025-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_authuser_date_joined_alter_authuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='authuser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
