# Generated by Django 5.2.1 on 2025-06-07 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_authuser_name_authuser_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Rang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новичок', max_length=255, null=True)),
            ],
            options={
                'db_table': 'rang',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('asset', models.CharField(max_length=255, null=True)),
                ('videoforwardid', models.CharField(max_length=255, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='NewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.note')),
            ],
            options={
                'db_table': 'newentry',
            },
        ),
        migrations.AddField(
            model_name='authuser',
            name='rang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rang'),
        ),
        migrations.CreateModel(
            name='NoteTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.note')),
                ('id_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tags')),
            ],
            options={
                'db_table': 'notetags',
            },
        ),
    ]
