# Generated by Django 5.2.1 on 2025-06-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_rang_tags_note_newentry_authuser_rang_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewEntry',
        ),
    ]
