# Generated by Django 5.2.1 on 2025-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tag',
        ),
        migrations.AddField(
            model_name='note',
            name='main_tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
