# Generated by Django 5.2.1 on 2025-06-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_category_tag_note_main_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetags',
            name='id_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notetags_set', to='app.note'),
        ),
    ]
