# Generated by Django 5.2.1 on 2025-06-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_notetags_id_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='site_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
