# Generated by Django 5.2.1 on 2025-06-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
