# Generated by Django 5.2.1 on 2025-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_note_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
