# Generated by Django 5.2.1 on 2025-06-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rank_userrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='rang',
        ),
        migrations.DeleteModel(
            name='Rang',
        ),
    ]
