# Generated by Django 5.2.1 on 2025-06-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_authuser_rang_delete_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='user_rank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userrank'),
        ),
    ]
