# Generated by Django 5.2.1 on 2025-08-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_board_options_remove_board_frequencies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AlterModelTable(
            name='board',
            table='boards',
        ),
    ]
