# Generated by Django 5.2.1 on 2025-08-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_board_options_alter_board_table'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telemetry',
            name='telemetry_ts_idx',
        ),
        migrations.RenameField(
            model_name='telemetry',
            old_name='type',
            new_name='gps',
        ),
        migrations.RenameField(
            model_name='telemetry',
            old_name='yaw',
            new_name='hdg',
        ),
        migrations.RenameIndex(
            model_name='telemetry',
            new_name='app_telemet_board_i_37fe9a_idx',
            old_name='telemetry_board_ts_idx',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='pretty',
        ),
        migrations.AddField(
            model_name='telemetry',
            name='arm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='sess',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='ts_epoch',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='last_mode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='gs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='mode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='ts',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['board', 'seq'], name='app_telemet_board_i_8e6853_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['sess'], name='app_telemet_sess_e28fae_idx'),
        ),
        migrations.AlterModelTable(
            name='telemetry',
            table=None,
        ),
    ]
