# Generated by Django 5.2.1 on 2025-08-30 21:26

import django.db.models.constraints
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_telemetry_telemetry_ts_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetry',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='telemetry',
            name='app_telemet_board_i_8e6853_idx',
        ),
        migrations.RemoveIndex(
            model_name='telemetry',
            name='app_telemet_sess_e28fae_idx',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='airspd',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='wind_e',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='wind_n',
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='mode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['sess', 'seq'], name='app_telemet_sess_3ee6f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='telemetry',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('board', 'sess', 'seq'), name='uniq_board_sess_seq'),
        ),
    ]
