# Generated by Django 5.2.1 on 2025-08-30 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_telemetry_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telemetry',
            new_name='telemetry_board_i_7b0818_idx',
            old_name='app_telemet_board_i_37fe9a_idx',
        ),
        migrations.RenameIndex(
            model_name='telemetry',
            new_name='telemetry_sess_2bd49d_idx',
            old_name='app_telemet_sess_3ee6f2_idx',
        ),
        migrations.AlterModelTable(
            name='telemetry',
            table='telemetry',
        ),
    ]
