# Generated by Django 5.2.1 on 2025-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_app_telemet_board_i_37fe9a_idx_telemetry_board_i_7b0818_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='last_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='last_pos_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
