# Generated by Django 5.2.1 on 2025-09-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_board_last_lat_board_last_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_offline_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='offline_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['is_online', 'last_telemetry_at'], name='boards_is_onli_e7ffd8_idx'),
        ),
    ]
