# Generated by Django 5.2.1 on 2025-09-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_board_last_offline_notified_at_board_offline_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='prolonged_offline_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
