# Generated by Django 5.2.1 on 2025-09-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_board_prolonged_offline_notified_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telemetry',
            name='telemetry_sess_2bd49d_idx',
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['board', 'sess', 'ts'], name='telemetry_board_i_7594df_idx'),
        ),
    ]
