# Generated by Django 5.2.1 on 2025-09-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_telemetry_telemetry_sess_2bd49d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='current_sess',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
