# Generated by Django 5.2.1 on 2025-09-06 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_board_current_sess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmSessionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sess', models.CharField(db_index=True, max_length=64)),
                ('arms_count', models.IntegerField(default=0)),
                ('armed_seconds', models.IntegerField(default=0)),
                ('armed_qstab_seconds', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.board')),
            ],
            options={
                'db_table': 'arm_session_stats',
                'indexes': [models.Index(fields=['board', 'sess'], name='arm_session_board_i_d06b1c_idx')],
                'unique_together': {('board', 'sess')},
            },
        ),
    ]
