# Generated by Django 5.2.1 on 2025-09-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_armsessionstat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArmSessionStat',
        ),
    ]
