# Generated by Django 5.2.1 on 2025-09-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_delete_armsessionstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_number', models.IntegerField(db_index=True)),
                ('ts', models.DateTimeField(db_index=True)),
                ('arms', models.IntegerField()),
                ('arm_sec', models.FloatField()),
                ('qstab_sec', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.board')),
            ],
            options={
                'db_table': 'arm_reports',
                'indexes': [models.Index(fields=['boat_number', 'ts'], name='arm_reports_boat_nu_37d6c7_idx')],
                'unique_together': {('boat_number', 'ts', 'arms', 'arm_sec', 'qstab_sec')},
            },
        ),
    ]
