# Generated by Django 5.2.1 on 2025-09-07 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_armreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'board_statuses',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('bot', 'Telegram Bot'), ('admin', 'Admin'), ('api', 'API')], default='bot', max_length=16)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='app.board')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_new', to='app.boardstatus')),
                ('previous_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_previous', to='app.boardstatus')),
            ],
            options={
                'db_table': 'board_movements',
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['board', '-created_at'], name='board_movem_board_i_16fb81_idx'), models.Index(fields=['new_status', 'created_at'], name='board_movem_new_sta_96c3fa_idx')],
            },
        ),
    ]
