# Generated by Django 5.2.1 on 2025-09-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_boardstatus_boardmovement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmovement',
            old_name='author',
            new_name='submitted_by',
        ),
        migrations.AddField(
            model_name='boardmovement',
            name='submitted_display',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
