# Generated by Django 5.2.1 on 2025-09-07 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_author_boardmovement_submitted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'board_sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardSectionTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('bot', 'Telegram Bot'), ('admin', 'Admin'), ('api', 'API')], default='bot', max_length=16)),
                ('submitted_display', models.CharField(blank=True, max_length=150, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_transfers', to='app.board')),
                ('from_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_from', to='app.boardsection')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_to', to='app.boardsection')),
            ],
            options={
                'db_table': 'board_section_transfers',
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['board', '-created_at'], name='board_secti_board_i_045133_idx'), models.Index(fields=['to_section', 'created_at'], name='board_secti_to_sect_ebc78a_idx')],
            },
        ),
    ]
