# Generated by Django 5.2.1 on 2025-09-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_boardsection_boardsectiontransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='app.boardsection'),
        ),
    ]
