# Generated by Django 5.2.1 on 2025-09-11 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_swap_fc_link_freq_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='flight_controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='app.flightcontroller'),
        ),
        migrations.AlterField(
            model_name='board',
            name='freq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='app.frequencyband'),
        ),
        migrations.AlterField(
            model_name='board',
            name='link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='app.linktype'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='board',
                    name='status',
                    field=models.ForeignKey(
                        to='app.BoardStatus',
                        on_delete=django.db.models.deletion.SET_NULL,
                        null=True, blank=True,
                        related_name='boards',
                        db_index=True,
                    ),
                ),
            ],
            database_operations=[
                # ничего не делаем в БД — колонки "status" сейчас нет
            ],
        ),
        migrations.AlterField(
            model_name='flightcontroller',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='frequencyband',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='linktype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
